language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
install:
  # Install coveralls (for coveralls.io integration)
  - pip install coveralls
  - pip install -r requirements.txt
script: python setup.py coverage
after_success: coveralls
