language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
install:
  # Install coveralls (for coveralls.io integration)
  - pip install coveralls
  - pip install -r requirements.txt
script: python setup.py coverage
after_success: coveralls
